- packages/umi-plugin-request/.gitignore
- packages/umi-plugin-request/LICENSE
- packages/umi-plugin-request/README.md
- packages/umi-plugin-request/example/.umirc.js
- packages/umi-plugin-request/example/src/app.js
- packages/umi-plugin-request/example/src/pages/index.css
- packages/umi-plugin-request/example/src/pages/index.js
- packages/umi-plugin-request/package.json
- packages/umi-plugin-request/src/index.ts
- packages/umi-plugin-request/src/request.js
use plugin in `.umirc.js`,
```js
export default {
plugins: [
['umi-plugin-request'],
],
}
```
config umi-request in `src/app.j|ts`
```js
export const request = {
prefix: 'abc1'
};
```
use in pages
```js
import request from 'alita-request';
request('/api/user');
```
> add umi-plugin-request

- .eslintrc
- packages/alita/src/plugins/generate/generators/app/index.ts
- packages/alita/src/plugins/generate/generators/app/templates/_gitignore
- packages/alita/src/plugins/generate/generators/app/templates/config/config.ts
- packages/alita/src/plugins/generate/generators/app/templates/mock/app.ts
- packages/eslint-config-alita/src/index.js
> fix g app no gitignore 

- packages/umi-plugin-cordova/src/index.ts
当en0没有IP时，尝试从其他网卡获取IP
修复这个 [bug](https://github.com/alitajs/alita/issues/14#issue-442604667)
> fix always get en0 interface bug, sometime en0 interface may inactive

- packages/umi-plugin-cordova/src/index.ts
ip地址可能是 `169.254.x.x` 这种保留地址，过滤掉
> filter reserved ip address

- packages/alita/src/plugins/index.ts
> add exclude public

- packages/alita/src/plugins/generate/generators/app/index.ts
> alita g app [appName]

- packages/umi-plugin-whale/src/index.ts
> h5 add default css style

- packages/alita/src/plugins/index.ts
> add convention authority

- packages/umi-plugin-cordova/src/index.ts
> change cordova side effect

- packages/alita/src/cli.ts
- packages/umi-plugin-cordova/src/index.ts
> Distinguish COMMAND implementation plugin

- packages/alita/package.json
- packages/alita/yarn.lock
```js
import { request } from 'alita';
request.use(async (ctx, next) => {
const { req } = ctx;
const { url, options } = req;
// 判断是否需要添加前缀，如果是统一添加可通过 prefix、suffix 参数配置
if (url.indexOf('/api') === 0) {
ctx.req.url = `/api/v1/${url}`;
}
ctx.req.options = {
...options,
};
console.log(111111111)
await next();
const { res } = ctx;
const { success = false } = res; // 假设返回结果为 : { success: false, errorCode: 'B001' }
if (!success) {
// 对异常情况做对应处理
}
})
```
> add request Middleware

- packages/umi-plugin-cordova/src/index.ts
> fix: ios 页面滚动会拖动最外层有抖动现象

- packages/umi-plugin-cordova/src/index.ts
> fix: android not import webkit

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/bug_report_cn.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/contributing.md
- any feature?
- close https://github.com/umijs/umi/ISSUE_URL
> feat: github tmp

- lerna.json
- packages/alita/types.d.ts
- packages/create-alita/package.json
- packages/routes/README.md
- packages/routes/package.json
- packages/routes/src/docs/README.md
- packages/routes/src/exclude.test.ts
- packages/routes/src/exclude.ts
- packages/routes/src/fixtures/exclude/.umirc.ts
- packages/routes/src/fixtures/exclude/pages/index.less
- packages/routes/src/fixtures/exclude/pages/index.tsx
- packages/routes/src/fixtures/exclude/pages/model.ts
- packages/routes/src/fixtures/update/.umirc.ts
- packages/routes/src/fixtures/update/pages/index.less
- packages/routes/src/fixtures/update/pages/index.tsx
- packages/routes/src/fixtures/update/pages/model.ts
- packages/routes/src/index.test.ts
- packages/routes/src/index.ts
- packages/umi-presets-alita/package.json
- packages/utils/package.json
- yarn.lock
真实的包在@umijs/plugin-routes，先发私包测试。
- any feature?
> feat: 过滤约定式路由

- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/fixtures/app-type-h5/.umirc.js
- packages/umi-presets-alita/src/fixtures/app-type-h5/pages/index.css
- packages/umi-presets-alita/src/fixtures/app-type-h5/pages/index.js
- packages/umi-presets-alita/src/fixtures/app-type-pc/.umirc.js
- packages/umi-presets-alita/src/fixtures/app-type-pc/pages/index.css
- packages/umi-presets-alita/src/fixtures/app-type-pc/pages/index.js
- packages/umi-presets-alita/src/fixtures/complex-route/.umirc.js
- packages/umi-presets-alita/src/fixtures/complex-route/pages/index.css
- packages/umi-presets-alita/src/fixtures/complex-route/pages/index.js
- packages/umi-presets-alita/src/fixtures/default-config/.umirc.js
- packages/umi-presets-alita/src/fixtures/dev/.umirc.js
- packages/umi-presets-alita/src/fixtures/dev/pages/index.css
- packages/umi-presets-alita/src/fixtures/dev/pages/index.js
- packages/umi-presets-alita/src/fixtures/main-path/.umirc.js
- packages/umi-presets-alita/src/fixtures/main-path/pages/home.js
- packages/umi-presets-alita/src/fixtures/main-path/pages/index.css
- packages/umi-presets-alita/src/fixtures/main-path/pages/index.js
- packages/umi-presets-alita/src/index.test.ts
- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/commands/cordova/cordova.ts
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
- packages/umi-presets-alita/src/plugins/features/appType.ts
- packages/umi-presets-alita/src/plugins/features/complexRoute.ts
- packages/umi-presets-alita/src/plugins/features/mainPath.ts
> feat: 完成alita需要的插件集

- packages/cordova/src/index.ts
- packages/native/README.md
- packages/native/package.json
- packages/native/src/fixtures/native/.umirc.js
- packages/native/src/fixtures/native/pages/index.css
- packages/native/src/fixtures/native/pages/index.js
- packages/native/src/index.test.ts
- packages/native/src/index.ts
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
> feat: init alita native

- packages/layout/README.md
- packages/layout/package.json
- packages/layout/src/docs/README.md
- packages/layout/src/index.ts
- packages/layout/src/layout/index.tsx
- packages/layout/src/utils/getLayoutContent.tsx
- packages/layout/src/utils/getModelContent.tsx
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- yarn.lock
> feat: plugin-mobile-layout

- packages/native/README.md
- packages/native/docs/README.md
- packages/native/src/fixtures/native/.umirc.js
- packages/native/src/fixtures/native/package.json
- packages/native/src/index.test.ts
- packages/native/src/index.ts
- packages/native/src/plugins.ts
- packages/native/src/utils.ts
- add alita-native plugin
- support install some plugins from config file
> alita native

- packages/native/src/fixtures/native/package.json
- packages/native/src/fixtures/native/plugins/fetch.json
- packages/native/src/index.ts
- packages/native/src/utils.test.ts
> feat: import native from alita

- packages/native/src/index.ts
> fix: native export error

- packages/cordova/README.md
- packages/create-alita/generate/generators/app/templates/package.json.tpl
- packages/create-alita/package.json
- packages/umi-presets-alita/src/plugins/commands/cordova/cordova.ts
> chore: cordova plugin change name

- packages/native/src/docs/README.md
> add alita-native usage

- lerna.json
- package.json
- packages/alita/package.json
- packages/dva/src/index.ts
- yarn.lock
> feat: update ts fix export 'XX' was not found in 'x'

- packages/cordova/src/index.ts
- packages/create-alita/package.json
- packages/umi-presets-alita/src/index.test.ts
- packages/umi-presets-alita/src/plugins/features/appType.ts
> feat: add config packageId displayName

- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/features/mainPath.ts
- packages/utils/src/resetMainPath/resetMainPath.test.ts
- packages/utils/src/resetMainPath/resetMainPath.ts
- yarn.lock
由于umi插件会运行两次，这里先规避处理了，增加了一个变量，判断是否已修改。
- any feature?
Close: https://github.com/alitajs/alita/issues/109
> feat: mainPath ，由于测试取不到别名，只能无测试上线

- packages/dva/src/connect.tpl
- packages/dva/src/index.ts
> fix: babel warning

- packages/router/README.md
- packages/router/package.json
- packages/router/src/index.ts
- packages/router/src/utils/getContent.tsx
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
> feat: umi/router

- packages/alita/index.js
- packages/cordova/src/index.ts
- packages/create-alita/src/AppGenerator/AppGenerator.ts
- packages/generate/src/generate/app.ts
> fix: src app import bug

- packages/keep-alive/src/index.ts
- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
- packages/keep-alive/src/utils/getLayoutContent.tsx
> feat: keep alive 配置支持正则

- packages/alita/src/cli.ts
- packages/umi-presets-alita/src/plugins/features/appType.ts
可以直接在项目 less 文件中使用antd的变量，而不需要在文件头增加 
```less
@import "~antd/es/style/themes/default.less";
```
`appType:pc` 能使用 antd 的变量，其他类型能使用 antd-mobile 的变量
- any feature?
> feat: 能在项目中直接使用 less 变量

- packages/layout/src/layout/index.tsx
> fix: set nav bar

- packages/cordova/src/index.ts
- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/features/displayName.ts
- packages/umi-presets-alita/src/plugins/features/packageId.ts
- yarn.lock
> fix: cordova config

- packages/alita/types.d.ts
> chore: alita config types

- packages/generate/templates/app/templates/tsconfig.json
- packages/retain-log/README.md
- packages/retain-log/package.json
- packages/retain-log/src/index.ts
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- packages/utils/src/px2hd/px2hd.test.ts
- packages/utils/src/px2hd/px2hd.ts
- tsconfig.json
- yarn.lock
> feat:umi ui

- packages/hd/src/fixtures/custom-hd/.umirc.ts
- packages/hd/src/fixtures/normal/.umirc.ts
- packages/umi-presets-alita/src/index.test.ts
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
> feat: Dynamic Routing

- packages/cordova/src/index.ts
- packages/tabs-layout/package.json
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
按条件加载插件，虽然插件里面也有过滤。心理上少用一些插件也好。
- any feature?
> feat: 按条件加载插件

- packages/tabs-layout/src/index.ts
- scripts/release.js
> chore: 测试自动刷cnpm

- packages/layout/src/layout/index.tsx
- packages/layout/src/utils/getModelContent.tsx
使用 `setTabBarList` 在页面级修改底部 Tabs 的信息，常用与动态修改 `badge` 。
`setTabBarList` 接收一个对象参数
| 属性 | 类型 | 必填 | 说明|
| --- | --- | --- | --- |
| pagePath | string | 是 | 页面路径，必须在 pages 中先定义|
| text | string | 是 | tab 上按钮文字|
| iconPath | string | 是 |图片路径，当 position 为 top 时，不显示 icon。|
| selectedIconPath | string | 是 |选中时的图片路径，当 position 为 top 时，不显示 icon。|
| iconSize | string | 否 |0.44rem|
| badge | string | 否 | badge |
| onPress | function | 否 | 点击事件 |
| title | string | 否 | 定义页面标题 |
- any feature?
> feat: setTabBarList

- package.json
- packages/alita/package.json
- packages/cordova/package.json
- packages/cordova/src/index.ts
- packages/create-alita/package.json
- packages/generate/templates/app/templates-pc/package.json.tpl
- packages/generate/templates/app/templates/package.json.tpl
- yarn.lock
> fix: cordova defaule config and update umi

- lerna.json
- package.json
- packages/alita/package.json
- packages/cordova/package.json
- packages/umi-presets-alita/package.json
- yarn.lock
> feat: update deps

- packages/layout/src/layout/index.tsx
- packages/layout/src/utils/getModelContent.tsx
> fix: Asynchronous modification layout config

- lerna.json
- package.json
- packages/alita/package.json
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
- yarn.lock
> feat: update umi3.1

- packages/keep-alive/package.json
- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
- any feature?
- close https://github.com/alitajs/alita/issues/140
> Keep alive convention routing

- packages/keep-alive/package.json
- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
> fix: 解除path-to-regexp新版本依赖

- packages/tabs-layout/src/utils/getTabsLayout.tsx
> feat: insert menu and use alias change tabname

- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- yarn.lock
> feat: add plugin-access-layout

- lerna.json
- packages/layout/package.json
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
- yarn.lock
> feat: support browser history

- packages/generate/templates/app/templates/mock/app.ts
- packages/generate/templates/app/templates/src/pages/index/index.less
- packages/generate/templates/app/templates/src/pages/list/index.tsx
- packages/generate/templates/app/templates/src/pages/settings/index.less
- packages/generate/templates/app/templates/src/services/api.ts
> 修改h5模板无法展示数据

- packages/access-layout/README.md
- packages/access-layout/package.json
- packages/access-layout/src/AccessLayout.tpl
- packages/access-layout/src/LayoutContent.tpl
- packages/access-layout/src/LayoutModel.tpl
- packages/access-layout/src/components.tpl
- packages/access-layout/src/docs/README.md
- packages/access-layout/src/index.ts
- packages/access-layout/src/utils/index.ts
- packages/access-layout/src/utils/runtimeUtil.ts
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
- yarn.lock
官方的包 review 太慢了，先发个私包测试用。
- any feature?
> feat: plugin-access-layout

- packages/layout/package.json
- packages/umi-presets-alita/src/plugins/features/appType.ts
- yarn.lock
> fix: root height

- .all-contributorsrc
- README.md
- package.json
- yarn.lock
> Chore all contributors cli

- packages/aconsole/README.md
- packages/aconsole/package.json
- packages/aconsole/src/index.ts
- packages/aconsole/src/inspx.tpl
- packages/aconsole/src/runtime.tpl
- packages/retain-log/src/index.ts
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.ts
- yarn.lock
> feat: add aconsole

- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
> fix: keep-alive page height

- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
> feat: keepalive占满容器

- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
> fix: keepalive占满容器

- packages/generate/templates/app/templates/package.json.tpl
- packages/layout/src/utils/getLayout.tsx
- packages/layout/src/utils/getModelContent.tsx
- packages/plugin-dva/src/index.test.ts
> Revert "feat: layout add changeTabList"

- packages/layout/src/utils/getLayout.tsx
- packages/layout/src/utils/getModelContent.tsx
setTabBarList 可以传递 {} 也可以传 []。
如果传递的pathname 原来有，就替换
如果原来没有，就增加。
如果对象里有 remove 就删除掉。
如果对象里有 replace 就替换掉。
> feat: tabBarList supports modification

- lerna.json
- packages/plugin-antd-mobile/README.md
- packages/plugin-antd-mobile/package.json
- packages/plugin-antd-mobile/src/index.ts
- packages/umi-presets-alita/package.json
- packages/umi-presets-alita/src/index.test.ts
- packages/umi-presets-alita/src/index.ts
- packages/umi-presets-alita/src/plugins/defaultConfig.ts
- packages/umi-presets-alita/src/plugins/features/mobile5.ts
- yarn.lock
> feat: mobile5

- .husky/commit-msg
- .husky/pre-commit
- scripts/verifyCommit.ts
merge https://github.com/umijs/umi-next/pull/288/files
> fix(husky): husky v7 commit msg verify

- .changeset/light-lies-own.md
- examples/boilerplate/src/models/todo.ts
- examples/boilerplate/src/pages/index.tsx
- packages/alita/src/features/config/config.ts
- packages/alita/src/preset.ts
- packages/plugins/src/model.ts
- packages/plugins/src/request.ts
```
import { useModel } from 'alita';
const { todos } = useModel('todo');
```
> feat: plugin usemodel

- .changeset/afraid-planets-greet.md
- examples/boilerplate/.umirc.ts
- examples/boilerplate/package.json
- examples/boilerplate/src/abc/index.tsx
- packages/alita/src/features/apptype.ts
- packages/plugins/src/mobile-layout.ts
- packages/plugins/templates/mobile-layout/layout5.tpl
- pnpm-lock.yaml
使用 mobile@5 的组件，重写 layout。
为了让旧项目平滑升级，api 兼容了旧的用法，和新的 mobile 参数。
> feat: mobile5-layout

- .changeset/quiet-pillows-kneel.md
- packages/plugins/src/model.ts
> chore: try ci

- .changeset/afraid-planets-greet.md
- .changeset/cold-comics-care.md
- .changeset/eight-seals-buy.md
- .changeset/four-apples-join.md
- .changeset/lemon-singers-film.md
- .changeset/light-lies-own.md
- .changeset/light-scissors-wink.md
- .changeset/quiet-pillows-kneel.md
- .changeset/red-masks-return.md
- .changeset/rotten-socks-tell.md
- .changeset/rude-dancers-live.md
- .changeset/serious-tools-marry.md
- .changeset/spicy-kids-care.md
- .changeset/wise-teachers-tie.md
- packages/plugins/src/aconsole.ts
- packages/plugins/templates/mobile-layout/layout5.tpl
fix: mobile5-layout tabbar active
fix: mobile-layout keepalive
chore: aconsole bottom env(safe-area-inset-bottom)
> fix: mobile5-layout keepalive

- .changeset/thick-bears-promis.md
- .changeset/thick-bears-promise.md
- packages/alita/src/preset.ts
- packages/native/package.json
- packages/plugins/src/antd.ts
feat: 按需加载插件
feat: 添加 antd 插件用于 pc 端
fix: 修复丢失的 homepage
> feat: add antd plugin

- .changeset/poor-berries-rescue.md
- packages/plugins/src/mobile-layout.ts
- packages/plugins/src/request.ts
- packages/plugins/templates/mobile-layout/model.tpl
- packages/request/src/index.ts
> feat: mobile-layout plugin types

- .changeset/yellow-chefs-begin.md
- packages/flow/src/components/Content/index.tsx
- packages/flow/src/components/Footer/index.tsx
- packages/flow/src/components/Header/index.tsx
- packages/flow/src/components/Page/index.tsx
- packages/flow/src/index.ts
将 @alita/react 中的几个常用组件，转移到 @alita/flow
> feat: page content header footer

- .changeset/khaki-planes-build.md
- packages/plugins/package.json
- packages/plugins/src/mobile-layout.ts
- pnpm-lock.yaml
Closes: https://github.com/alitajs/alita/issues/270
> fix: antd icons no find

- .changeset/famous-scissors-invite.md
- packages/plugins/templates/hd/hd.tpl
hd plugin中针对键盘弹起的情况，这边做出一点补充。同时readme中也可增加自定义方案的引入方式，这边暂未找到相应文件进行补充。
> fix: hd while keyboardChange

- lerna.json
- packages/keep-alive/src/index.ts
- packages/keep-alive/src/utils/getKeepAliveLayout.tsx
支持动态配置 keepalive 
```
export function getKeepAlive(keealive) {
return ['/list'];
}
```
> feat: alita@2 keep alive support runtime

- .changeset/strange-planes-breathe.md
- packages/native/src/index.ts
> fix(native): fix native npm client error

- .changeset/metal-lies-repeat.md
- packages/plugins/src/aconsole.ts
change vconsole introduction mode
> 309 vconsole

- docs/README.md
- docs/README.zh-CN.md
跳转链接修改成 /docs/introduce/introduce
> fix: button error route

- docs/components/README.md
- docs/docs/README.md
- docs/docs/README.zh-CN.md
- docs/locales/zh-CN.json
- package.json
- theme.config.ts
> fix: docs paths

- docs/docs/guides/native.md
- theme.config.ts
> docs: native docs

- .changeset/tall-dolls-exercise.md
- packages/plugins/src/hd.ts
> Fix antd mobile root hd

- .changeset/config.json
- .changeset/few-trees-do.md
- examples/helmet/package.json
- examples/helmet/src/pages/index.tsx
- examples/helmet/tsconfig.json
- examples/helmet/typings.d.ts
- packages/alita/src/preset.ts
- packages/plugins/package.json
- packages/plugins/src/helmet.ts
- pnpm-lock.yaml
```tsx
import { Helmet } from 'alita';
import React from 'react';
const App = () => (
<>
<Helmet>
<title>Hello World</title>
<link rel="canonical" href="https://www.tacobell.com/" />
</Helmet>
<h1>Hello World</h1>
</>
);
export default App;
```
> feat: react-helmet-async

- .changeset/empty-poets-report.md
- .umirc.ts
- docs/docs/api/runtime-config.md
- examples/boilerplate/src/app.tsx
- package.json
- packages/plugins/templates/keepalive/context.tpl
- packages/plugins/templates/keepalive/runtime.tpl
- pnpm-lock.yaml
export async function getKeepAlive(keepaliva: any[]) {
console.log('getKeepAlive');
console.log(keepaliva);
return [/users/];
}
> feat: async getKeepalive

- .all-contributorsrc
- README.md
新增 @532pyh 文档协作者
增加 @hang1017 代码开发
> chore: ac add 532pyh hang1017

- .changeset/swift-zoos-look.md
- examples/tabs/.umirc.ts
- examples/tabs/src/app.tsx
- examples/tabs/src/layouts/index.tsx
- packages/plugins/src/keepalive.ts
- packages/plugins/templates/keepalive/context.tpl
配置 
```ts
{
path: '/',
redirect: '/users',
},
```
且 ‘/’ 保持时，会造成死循环
> feat: keepalive redirect

- .changeset/fluffy-radios-applaud.md
- examples/boilerplate/src/app.tsx
- examples/boilerplate/src/pages/users/index.tsx
- packages/alita/hackumi.js
- packages/alita/package.json
- packages/alita/templates/umi.tpl
- pnpm-lock.yaml
https://github.com/umijs/umi/pull/9765
紧急修复这个问题
> feat: hack umi tmp

- .all-contributorsrc
- README.md
https://github.com/alitajs/alita/pull/477
> feat: ac add tangbzai

- .changeset/slimy-actors-own.md
- packages/plugin-lowcode/src/index.ts
> fix: lib/codemirror 404

- .changeset/afraid-readers-deliver.md
- packages/plugins/src/keepalive.ts
- packages/plugins/src/tabs-layout.ts
- packages/plugins/templates/keepalive/context.tpl
为 tabs-layout 和 keep-alive 插件添加 hasFixedHeader 配置
fixed: https://github.com/alitajs/alita/issues/478
> feat: add hasFixedHeader config for tabs-layout and keep-alive plugin

- .all-contributorsrc
- README.md
https://github.com/alitajs/alita/pull/483
> feat: ac add hexi1997

- .changeset/cold-toes-do.md
- docs/docs/guides/tabs.md
- examples/tabs/.umirc.ts
- examples/tabs/src/app.tsx
- examples/tabs/src/pages/foo/index.tsx
- examples/tabs/src/pages/index.tsx
- packages/plugins/src/keepalive.ts
- packages/plugins/templates/keepalive/context.tpl
- packages/plugins/templates/keepalive/runtime.tpl
Closes: https://github.com/alitajs/alita/issues/501
> feat: support antd tabs props

- .changeset/pretty-plants-chew.md
- .changeset/rich-dragons-trade.md
- docs/docs/guides/tabs.md
- examples/tabs/.umirc.ts
- examples/tabs/package.json
- examples/tabs/src/layouts/index.tsx
- packages/plugins/templates/keepalive/context.tpl
fix: https://github.com/alitajs/alita/issues/506
> fix: hasFixedHeader style error on example/tabs demo

- .changeset/seven-pumpkins-relate.md
- .changeset/tricky-foxes-taste.md
- examples/tabs/.umirc.ts
- examples/tabs/src/locales/en-US.ts
- examples/tabs/src/locales/zh-CN.ts
- examples/tabs/src/pages/users/index.tsx
- packages/plugins/templates/keepalive/context.tpl
Closes: https://github.com/alitajs/alita/issues/484
> feat: tabs工具栏支持国际化

- .changeset/fast-knives-repeat.md
- packages/plugins/templates/keepalive/context.tpl
templates 操作之眼瞎科技@chj-damon 哈哈哈
> fix: keepalive tpl

- .changeset/tough-points-speak.md
- packages/plugins/templates/keepalive/context.tpl
Closes: https://github.com/alitajs/alita/issues/535
> fix: tabs other

- .changeset/proud-countries-report.md
- docs/docs/guides/tabs.md
- examples/alita2/config/config.ts
- examples/tabs/src/pages/index.tsx
- examples/tabs/src/pages/users/index.tsx
- packages/plugins/src/keepalive.ts
- packages/plugins/templates/keepalive/context.tpl
Closes: https://github.com/alitajs/alita/issues/509
可以在操作完成之后，手动调用 closeTab 方法关闭
```ts
import { closeTab } from 'alita || umi || @umijs/max';
closeTab(pathname);
```
> feat: closeTab

- .changeset/tall-toes-protect.md
- .changeset/yellow-items-hope.md
- examples/tabs/.umirc.ts
- examples/tabs/src/app.tsx
- examples/tabs/src/layouts/index.tsx
- examples/tabs/src/pages/lowerCase/index.tsx
- packages/plugins/templates/keepalive/context.tpl
- packages/plugins/templates/keepalive/runtime.tpl
修复 tabs pathname 大小写问题，主要表现是 无法关闭 tabs
顺便给自定义 tabs 传递参数，Closes: https://github.com/alitajs/alita/pull/558
> Fix tabs pathname

- .changeset/chilled-brooms-rule.md
- packages/alita/src/features/legacy.ts
- packages/plugins/src/aconsole.ts
- packages/plugins/src/antd.ts
- packages/plugins/src/antdmobile.ts
- packages/plugins/src/classnames.ts
- packages/plugins/src/dva.ts
- packages/plugins/src/hd.ts
- packages/plugins/src/keepalive.ts
- packages/plugins/src/mainpath.ts
- packages/plugins/src/max/initial-state.ts
- packages/plugins/src/max/locale.ts
- packages/plugins/src/mobile-layout.ts
- packages/plugins/src/model.ts
- packages/plugins/src/request.ts
- packages/plugins/src/tabs-layout.ts
> Plugins work in setup

- .changeset/friendly-planets-hug.md
- .github/workflows/deploy.yml
- .workflow/branch-pipeline.yml
- .workflow/pr-pipeline.yml
- examples/mobile5/src/app.tsx
- packages/plugins/templates/mobile-layout/layout.tpl
- packages/plugins/templates/mobile-layout/layout5.tpl
修复 mobile5 配置不生效问题
Closes: #601
> fix: mobile5 select color

- .changeset/slimy-chairs-perform.md
- packages/plugins/templates/mobile-layout/layout.tpl
- packages/plugins/templates/mobile-layout/layout5.tpl
> fix: emitter subscription error

- .changeset/dirty-buttons-poke.md
- packages/plugins/src/max/locale.ts
fix: resolve locale error in custom command. https://github.com/alitajs/alita/issues/639
> fix: resolve locale error in custom command.
